name: Build and deploy Python app to Azure Web App - myragbot-app-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write     # 👈 needed for azure/login
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5FAAD864154A40B2B275243D82F7BBAE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_40DB3C2D1C144667ACE9AEB0AC9BAEF6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9DC2D4B99EEA45A8992A26BDA07DD9C4 }}

      - name: Deploy to Azure Web App with Oryx build
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myragbot-app-service'
          slot-name: 'Production'
          package: .
          enable-oryx-build: true
