name: Build and deploy Python app to Azure Web App - myragbot-app-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5FAAD864154A40B2B275243D82F7BBAE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_40DB3C2D1C144667ACE9AEB0AC9BAEF6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9DC2D4B99EEA45A8992A26BDA07DD9C4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myragbot-app-service'
          slot-name: 'Production'
          package: .
